language: node_js
node_js:
- 12
sudo: required
services:
- docker
env:
  global:
  - REGISTRY_USER=pjotre86
  - secure: hfWI8q1y8KdpEgNSSG1OoJgjnMU6kAOPaE0riEGmuUs7pEvsy7gVJSPX5ooa8weJAb2WTcdbPLtRFt09n37xj7MduaFikd2BHj52mBhdoG9d2+J0TI51L+6KrDHg4RlIKuD9vvbR+Xqv9FWDK5N94xB/TRIKajMCYVUGhw6WvAoH/2jHqMB3yiPB8TpXwuLep3BeUY/sCSAeRgifYNd401CN9/2jiGNPcOfXGdc+YLp9Zt7wvjxmpptG4xPeZeWh11nPP1pl3KE5q27wSYugSLgjQuYH2BkLWUa9/v21oCYhQek4HUjRnAE4JB9sWhqx73oawcjcsdV+/aul08f6CVbh5AnVYdTjWe/PjL0vynbDxOWo8z5YLR+DIWnfLiwyaXLNvUrOwl6De0mqHVCpGjlgqLF+apVXxxG/3dNm86aY2YxcsEoQcnE8GeLTvcDB7VlSmpcnn0n6JBW6MrI/HnseH0PSKQrngWJIe+zU0iZvXp8nms9+C0I+f6vt5v82KMWnvf/gPWFzWzgyYgzDOXUwIjsJ85GpH/vuWkhVOTmAHMblj2k7AypeFcBofZ9g/khi1xQ3XCtRYK8r1PK9CgnmY4++CT3TW5pwwkSzpUkoH6m0DT/ydV8bJ1Sqc4hBY19DrFwDlrbhojxUH6sRBfpWOG3yiEl412PntiiMgO0=
  - secure: 2X7qmT/a4QZMlN+N2rCRECSgcLKLfZQVOnmJ+Wy5JE1dczDzPkgYVHMQKNuJnx2kGipNM3ZpZpIBnDUJa0HyCAODya5+ivhmFeucAGcvEAUIQR8HRcyrBekMZx08fadKP6Lyp+zHt0DNgjHy4VPeeTFebZ45tzVR4MB27wfhMWxGvNxIKtMI9s5Eoz2zZsHwUxq2NTKS0wkY/s+9KTKSF3JPD3VEqIf8gCXbc1T8+xQSPdG1n+LjQdTGbpOYi7gksWX+5EeW1daAnGh/asdIyQcOGX9C1djFFNgY+xEzRaSo5oNHDaYi21t0V0ciwo3jvc94w8BcVr99YFx03x4a2Q43vomtpLbSM1AaVnZAC7NCe7fiMiAKBKs5jDi7AXn5chTlCPeMFM68jeyggyi94cHyi+mNn/LiONBiMXcS5Ig/Qj57L/k47dD8c9fn7Z/RlOzhmiZ7bJ2OrdxjticLo04HhBaty0TaKWRAqSm8Q9618SQ83eDS+hvblqrNVQEu08CU6f8G72U7V01AGNDv4vWg9G6tlFgmIe9Pzh1l5h4FoJh0OpeVrx4qIPhbQt7YF2fn6Yt6H2ZSnVzYFUTQLyK6oVGnu1ycclOwz799rh9diV8FtSA68zqbqSezhS8Aq0XAk6N3VRtjUtJnx3YV+X/vM3zP68gmPNRWUtnK6Vc=
cache:
  directories:
  - "$HOME/.yarn-cache"
before_script:
- nvm install lts/*
- npm install @semantic-release/git @semantic-release/changelog semantic-release@15
after_success:
- npx semantic-release
script: true
before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
- provider: script
  script: bash ./deploy.sh ${TRAVIS_BRANCH}
  skip_cleanup: true
  on:
    branch: dev
- provider: script
  script: bash ./deploy.sh ${TRAVIS_BRANCH}
  skip_cleanup: true
  on:
    branch: master
