FROM node:13.5-alpine

# create destination directory
RUN mkdir -p /usr/src/nuxt-app
WORKDIR /usr/src/nuxt-app

# update and install dependency
RUN apk update && apk upgrade
RUN apk add git

# copy the app, note .dockerignore
COPY package.json /usr/src/nuxt-app/

RUN npm install

COPY . /usr/src/nuxt-app/

# expose 5000 on container
EXPOSE 5000

# set app serving to permissive / assigned
ENV NUXT_HOST=0.0.0.0
# set app port
ENV NUXT_PORT=5000

#ENV graphql_host=http://corphub-backend-service-dev:8082
#ENV elastic_search_host=http://10.99.55.152:9200
#ENV graphql_endpoint=http://corphub-backend-service-dev:8082/graphql


# start the app
CMD [ "npm", "run", "dev" ]
